name: local_repo
description: Local repositories. Provision API endpoints to persist data on the local storage.
version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^7.0.1
  freezed_annotation: ^2.1.0
  clock: ^1.1.0
  path_provider: ^2.0.14
  file: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.7
  freezed: ^2.1.0+1
  hive_generator: ^1.1.2
  json_serializable: ^6.1.4
  mocktail: ^0.3.0
  plugin_platform_interface: any
  path_provider_platform_interface: any

flutter:
