name: template_theme
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.0
  shimmer: ^2.0.0
  equatable: ^2.0.5
  google_fonts: ^3.0.1
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.1.0
  stateful: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  recase: ^4.0.0
  clock: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
