name: app_template
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  template_theme:
    path: ../template_theme
  local_repo:
    path: ../repositories/local_repo
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  go_router: ^6.0.10
  equatable: ^2.0.5
  package_info_plus: ^3.0.2
  reactive_forms: ^14.1.0
  stateful: ^0.2.1
  freezed_annotation: ^2.1.0
  # Services and utils packages
  # Error reporting and monitoring
  sentry_flutter: ^6.18.2
  # Local repo
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true
